version: '3.8'
services:
  chrome-test:
    build: .
    shm_size: '2gb'
    environment:
      - DISPLAY=:99  # Для Xvfb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Для GUI (если нужно)
      - ./target:/app/target
    cap_add:
      - SYS_ADMIN  # Требуется для работы браузера в контейнере